/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='homepage mob-bg'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12 glob-cta'>
        <div className='top-star-object'>
          <img src='/meta/Metaversol Icon_LightPurple_OK 1.png' alt='start' />
        </div>
        <div className='bottom-star-object'>
          <img src='/meta/start-first-section.png' alt='start-first-section.png' />
        </div>
        <div className='position-relative max-w-7xl mx-auto px-4'>
          <div className="grid grid-cols-12 xl:gap-12 lg:gap-8 gap-4">
            <div className="md:col-span-5 col-span-12">
              <h1 className='xl:text-6xl lg:text-6xl md:text-4xl text-4xl font-bold text-white lg:mb-12 mb-8'>
                A virtual,
                infinitely
                expanding
                universe.
              </h1>

              <div className='btn-alpha-wrap relative'>
                <div className='btn-alpha-blur'>
                </div>
                <button className="font-medium btn-alpha">
                  Explore
                </button>
              </div>
            </div>
            <div className="md:col-span-7 col-span-12">
              <div className='text-left w-full'>
               <div className='max-w-xl text-left w-full'>
               <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-4 mb-2'>
                  The Expanse is comprised entirely of the projects and businesses that we have brought onboard  our platform.
                </p>
               </div>
                <div>
                  <img src='/assets/images/ChainCta.png' alt='ChainCta' />
                </div>
              </div>
            </div>
          </div>
        </div>

      </section>

      <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12'>
        <div className='expanse-object-1'>
          <img src='/meta/planet-5.png' alt='planet-5' />
        </div>
        <div className='max-w-7xl mx-auto px-4'>
          <div className='lg:mb-24 mb-8'>
            <h2 className='position-relative xl:text-5xl lg:text-4xl text-3xl font-bold text-white text-center'>
              WELCOME TO THE EXPANSE
            </h2>
          </div>
          <div className="flex justify-around lg:flex-nowrap flex-wrap lg:gap-12 gap-4">
            <div>
              <img className='position-relative max-w-2xl w-full' src='/assets/images/welcomeBanner.png' alt='welcomeBanner' />
            </div>
            <div>
              <div className='max-w-xl text-left w-full'>
                <h4 className='xl:text-3xl text-2xl  text-purple font-bold mb-6'>
                  This is more than a social experience
                </h4>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  It isnt just a place to play games or look at your NFTs.
                  The Expanse adds layers of experience and opportunities to the real world.
                </p>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  Its a place to work, do business, build communities, and augment reality. Its where we come together and build the future.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12'>
        <div className='expanse-object'>
          <img src='/meta/4Planet.png' alt='4Planet' />
        </div>
        <div className='create-world-object-1'>
          <img src='/meta/5star.png' alt='planet-5' />
        </div>
        <div className='max-w-7xl mx-auto px-4 position-relative'>
          <div className='lg:mb-4 mb-4'>
            <h2 className='special-heading xl:text-5xl lg:text-4xl text-3xl font-bold text-white text-center'>
              CREATE YOUR WORLD
            </h2>
          </div>
          <div className="flex justify-around items-center lg:flex-nowrap flex-wrap lg:flex-row flex-col-reverse lg:gap-12 gap-8">
            <div>
              <div className='max-w-xl text-left w-full '>
                <h4 className='xl:text-3xl text-2xl  text-purple font-bold mb-6'>
                  Reality is a construct. Heres your chance to build it.
                </h4>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  Design your projects world. Create a massive steampunk metropolis, rustic countryside towns, or magnificent ivory towers; the possibilities are endless
                </p>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  Develop a game for your world, or add other utility for your holders such as shops, museums, etc.
                </p>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  Modify your worlds landscape and create the perfect atmosphere for your project.
                </p>

                <div className='btn-alpha-wrap relative'>
                  <div className='btn-alpha-blur'>

                  </div>
                  <button className="font-medium btn-alpha">
                    Explore
                  </button>
                </div>
              </div>
            </div>
            <div>
              <img className='md:max-w-2xl max-w-1xl w-full hidden sm:block' src='/assets/images/worldBanner.png' alt='worldBanner' />
              <img className='md:max-w-2xl max-w-1xl w-full sm:hidden block' src='/assets/images/centerGlobMob.png' alt='worldBanner' />
            </div>
          </div>
        </div>
      </section>

      <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12 pb-16 galaxy-bg'>
        <div className='expanse-object-mini'>
          <img src='/meta/shallow-planet.png' alt='planet-5' />
        </div>
        <div className='max-w-7xl mx-auto px-4 position-relative'>
          <div className='lg:mb-24 mb-8'>
            <h2 className='special-heading xl:text-5xl lg:text-4xl text-3xl font-bold text-white text-center'>
              METAVERSOL PASS
            </h2>
          </div>
          <div className="grid grid-cols-1 lg:gap-12 gap-4 items-center">
            <div>
              <div className='max-w-5xl w-full mx-auto text-center'>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  The Expanse is intended to be a free-to-use platform, and no purchases will be required to log in and play with your friends.
                </p>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  There will be a paid option in the form of a Metaversol Pass, this pass is not required, but does provide a number of benefits (none of which are designed to make a holder more powerful than a free-to-play player).
                </p>
                <p className='text-white xl:text-xl lg:text-xl md:text-xl text-md lg:mb-10 mb-6'>
                  The Pass will be available January, 2022 and the price is undetermined.
                </p>

                <div className='flex justify-center'>
                  <div className='btn-alpha-wrap relative'>
                    <div className='btn-alpha-blur'>

                    </div>
                    <button className="font-medium btn-alpha">
                      Learn More
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* <section className='xl:pt-40 lg:pt-32 md:pt-24 pt-12'>
        <div className='founder-object-2'>
          <img src='/meta/planet-5.png' alt='planet-5' />
        </div>
        <div className='founder-object-1'>
          <img src='/meta/5star.png' alt='5star' />
        </div>
        <div className='founder-object-3'>
          <img src='/meta/earth-planet.png' alt='earth-planet' />
        </div>
        <div className='max-w-7xl mx-auto md:px-4 px-8 position-relative'>
          <div className='lg:mb-24 mb-8'>
            <h2 className='special-heading xl:text-5xl lg:text-4xl text-3xl font-bold text-white text-center'>
              MEET THE FOUNDERS
            </h2>
          </div>
          <div className="founder-cards grid md:grid-cols-2 grid-cols-1 lg:gap-12 gap-4 items-center ">
            <div className='flex justify-center'>
              <div className=' border-purple bg-blue-10 w-102 p-11 rounded-3xl border-4'>
                <div className='flex justify-center flex-col items-center mb-8'>
                  <img src='/assets/images/Solanacoin1.png' alt='Solanacoin1' />
                </div>
                <h5 className='xl:text-3xl text-2xl text-purple font-bold mb-6 text-center'>CHARLES POOLE</h5>
                <p className='text-white lg:text-xl md:text-xl text-md text-center lg:mb-10 mb-6'>
                  Charles is the wizard behind The Expanse. With over a decade of experience in Virtual Reality game development, he has been a pioneer in the industry since day one.
                </p>
              </div>
            </div>
            <div className='flex justify-center'>
              <div className=' border-purple bg-blue-10 w-102 p-11 rounded-3xl border-4'>
                <div className='flex justify-center flex-col items-center mb-8'>
                  <img src='/assets/images/Solanacoin1.png' alt='Solanacoin1' />
                </div>
                <h5 className='xl:text-3xl text-2xl text-purple font-bold mb-6 text-center'>CHARLES POOLE</h5>
                <p className='text-white lg:text-xl md:text-xl text-md text-center lg:mb-10 mb-6'>
                  Charles is the wizard behind The Expanse. With over a decade of experience in Virtual Reality game development, he has been a pioneer in the industry since day one.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section> */}
      <Footer />
    </div>
  )
}
