/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='homepage mob-bg'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      


      <section className='position-relative xl:pt-40 lg:pt-32 md:pt-24 pt-12' >
      <div className='expanse-object-1-team'>
          <img src='/meta/planet-5.png' alt='planet-5' />
        </div>
        <div className='expanse-object-2-team'>
        <img src='/meta/start-first-section.png' alt='start-first-section.png' />
        </div>
        <div className='max-w-7xl mx-auto px-4'>
          <div className='lg:mb-40 mb-20'>
            <h2 className='xl:text-5xl lg:text-4xl text-3xl font-bold text-white text-center'>
              MEET THE FOUNDERS
            </h2>
          </div>
          <div className="grid md:grid-cols-2 grid-cols-1 lg:gap-12 gap-4 items-center ">
            <div className='flex justify-center'>
              <div className=' border-purple bg-blue-10 w-102 p-11 rounded-3xl border-4'>
                <div className='flex justify-center flex-col items-center mb-8'>
                  <img src='/assets/images/Solanacoin1.png' alt='Solanacoin1' />
                </div>
                <h5 className='xl:text-3xl text-2xl text-purple font-bold mb-6 text-center'>CHARLES POOLE</h5>
                <p className='text-white lg:text-xl md:text-xl text-md text-center lg:mb-10 mb-6'>
                  Charles is the wizard behind The Expanse. With over a decade of experience in Virtual Reality game development, he has been a pioneer in the industry since day one.
                </p>
              </div>
            </div>
            <div className='flex justify-center'>
              <div className=' border-purple bg-blue-10 w-102 p-11 rounded-3xl border-4'>
                <div className='flex justify-center flex-col items-center mb-8'>
                  <img src='/assets/images/Solanacoin1.png' alt='Solanacoin1' />
                </div>
                <h5 className='xl:text-3xl text-2xl text-purple font-bold mb-6 text-center'>CHARLES POOLE</h5>
                <p className='text-white lg:text-xl md:text-xl text-md text-center lg:mb-10 mb-6'>
                  Charles is the wizard behind The Expanse. With over a decade of experience in Virtual Reality game development, he has been a pioneer in the industry since day one.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  )
}
